### ISSUE TITLE
CPU Core starts from 2

### ISSUE THREAD

**Issue by arvenil** [dkorunic/iSMC#14]
<img width="636" alt="image" src="https://user-images.githubusercontent.com/450355/182018645-ceaeedaf-8100-4c87-a8e8-0ed4c7799135.png">

**Comment by dkorunic** [comment]
@arvenil It's a non-issue, since TC0C was probed and there was no sensible response, so we went on with TC1C etc. up to TC9C when enumerating SMC keys. Since counting for cores starts with 0 (TC0C is CPU Core 1), this means that for some odd reason SMC on your boards starts with the wrong offset.
