### ISSUE TITLE
'BATP' key doesn't align with whether computer runs on battery power

### ISSUE THREAD

**Issue by DUOLabs333** [dkorunic/iSMC#16]
On my M1 Macbook, iSMC reports that the Macbook is not on battery power regardless of whether it's plugged in or not. It seems that `BATP` doesn't exist on M1 systems.

**Comment by dkorunic** [comment]
@DUOLabs333 That is correct and it's not an issue, BATP is a SMC key and battery status in M1 is only obtainable through HIDDriverKit and I'm not there yet..
