### ISSUE TITLE
TW0P Missing

### ISSUE THREAD

**Issue by dhyanKaro** [dkorunic/iSMC#21]
Just comparing istats scan to iSMC output.
istats has `TW0P AirPort Proximity`.
It'd be nice to see it in iSMC too.

**Comment by dkorunic** [comment]
Dear @dhyanKaro, it's already [included](https://github.com/dkorunic/iSMC/blob/9850551304f494ee1822739b4a4fc279f6144d5c/src/temp.txt#L166) and it should work, as long as the value can be parsed.
