### ISSUE TITLE
Temp Threshold regards to Fan Control

### ISSUE THREAD

**Issue by XEF2ZQ** [dkorunic/iSMC#24]
So with this I can edit the behavior of the SMC controller so that the fans kick in earlier than insane 95c degree?

**Comment by dkorunic** [comment]
@XEF2ZQ I would recommend for that specific purpose to use excellent [TG Pro](https://www.tunabellysoftware.com/tgpro/).

**Comment by XEF2ZQ** [comment]
yeah that only works when the system kicks in the fans and that threshold is 95c. And that is not healthy. Until the system starts the fans, 3rd party app can't do anything. And once the system shuts it down at 80c temp, again control is cut from rd party app

**Comment by dkorunic** [comment]
@XEF2ZQ TG Pro is able to completely override system fan control and you can write your own rules.
