### ISSUE TITLE
Writing to SMC keys

### ISSUE THREAD

**Issue by jlehrer1** [dkorunic/iSMC#4]
Hi,

I can't believe I haven't found this repo before! Incredible. I didn't think I'd be able to find the new SMC keys. Anyways, is there a way to write values to these keys? For context, I'm trying to write an open source Fan Control app for the T2 Intel Macs, and `smcFanControl` no longer works on Catalina.

**Comment by dkorunic** [comment]
Hey @jlehrer1 , you can write values to keys by importing `github.com/panotza/gosmc` and calling `gosmc.SMCWriteKey()`. Make sure to read key first with `gosmc.SMCReadKey()` to get `DataSize` and `DataType` as you will need to know those for value conversions (for more info see [conv.go](https://github.com/dkorunic/iSMC/blob/master/smc/conv.go)) and for `gosmc.SMCWriteKey()` calls.
