### ISSUE TITLE
Set fan speed

### ISSUE THREAD

**Issue by quackduck** [dkorunic/iSMC#5]
How would I be able to set fan speeds using this?

**Comment by dkorunic** [comment]
@quackduck Sadly, tool is used just for discovery and printout of SMC keys and values. For controlling fan speeds, i would recommend pretty great [TG Pro](https://www.tunabellysoftware.com/tgpro/) or [Macs Fan Control](https://crystalidea.com/macs-fan-control) which are meant for this kind of operation.

**Comment by quackduck** [comment]
Nah, I wanted to be able to do it programmatically. I ended up using the CLI of smcFanControl.

Why wouldn't you add write functionality?
