### ISSUE TITLE
Deprecation warning shown during build

### ISSUE THREAD

**Issue by roele** [dkorunic/iSMC#6]
While building the executable (MacBook M1 Pro, macOS 12.3.1) the following warning is shown.

```
 ❯ go build .
# github.com/panotza/gosmc
smc.c:73:5: warning: 'IOMasterPort' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:132:1: note: 'IOMasterPort' has been explicitly marked deprecated here
```

**Comment by dkorunic** [comment]
Hi @roele , that's expected and comes from `panotza/gosmc`, it being an interface for old SMC.c Apple leak. I can't do anything there, but we are lucky that it still works.

**Comment by ngie-eign** [comment]
The project should be forked and fixed. That's the way to resolve the issue..
